# -*- coding: utf-8 -*-
"""finaltraing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fqoB-6zyqAn9gkW_zgAw6RrHZjw0zKy
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
from torchvision.models import vit_b_16, ViT_B_16_Weights
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image, ImageOps #standard torch image library
import os

# =====================
# PATHS
# =====================
DATA_DIR = "/content/drive/MyDrive/THEFUCK/dataset"
SAVE_DIR = os.path.join(os.path.dirname(DATA_DIR), "Weights_ViT")
os.makedirs(SAVE_DIR, exist_ok=True)

# =====================
# CONFIG
# =====================
IMG_SIZE = 224
BATCH_SIZE = 64
EPOCHS = 40
LR = 1e-4
NUM_WORKERS = 2

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

MEAN = [0.474015, 0.538135, 0.587003] #fine tuning from previous traing NOT from ImageNet
STD  = [0.201344, 0.201758, 0.194989] #for first time training weights can be take from image net since this is custom dataset

IMG_EXTENSIONS = (".jpg", ".jpeg", ".png")

# =====================
# DATA COLLECTION
# =====================
def collect_image_paths(root_dir):
    image_paths = []
    class_names = []

    for root, _ , files in os.walk(root_dir): #travesing the root directory (_ means subfolders)
        valid_files = [f for f in files if f.lower().endswith(IMG_EXTENSIONS)] #so that only given extentions are acepted
        if len(valid_files) > 0: #the actual files should be present more than one
            class_names.append(os.path.basename(root))
            image_paths.extend([os.path.join(root, f) for f in valid_files]) #the paths for train and val are defined

    class_names.sort() #alphabetic sorting of class names
    return image_paths, class_names

#this is to call all training images and load all the training and val images
train_paths, class_names = collect_image_paths(os.path.join(DATA_DIR, "train"))
val_paths, _ = collect_image_paths(os.path.join(DATA_DIR, "val"))


if len(train_paths) == 0 or len(val_paths) == 0: #if this shit doesnt exist(can be ignored but this helped me mount the google drive)
    raise RuntimeError("Train or Val dataset is EMPTY. Check directory structure.")

CLASS_TO_IDX = {cls: i for i, cls in enumerate(class_names)} #this is for numeric mapping of the two gesture classes
NUM_CLASSES = len(class_names)

print("Classes:", class_names)
print("Train samples:", len(train_paths))
print("Val samples:", len(val_paths))

with open(os.path.join(SAVE_DIR, "class_names.txt"), "w") as f:
    f.write("\n".join(class_names)) #this is for safety(a text file having classnemes to ensure code is working)

# =====================
# TRANSFORMS
# =====================
class ResizeWithAspectRatio:
    def __init__(self, size):
        self.size = size

    def __call__(self, img):
        w, h = img.size
        scale = min(self.size / w, self.size / h)
        nw, nh = int(w * scale), int(h * scale)
        img = img.resize((nw, nh), Image.BICUBIC)

        pad_w = self.size - nw
        pad_h = self.size - nh
        img = ImageOps.expand(
            img,
            (pad_w // 2, pad_h // 2, pad_w - pad_w // 2, pad_h - pad_h // 2),
            fill=0
        )
        return img

train_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(p=0.5),
    ResizeWithAspectRatio(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

val_transform = transforms.Compose([
    ResizeWithAspectRatio(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

# =====================
# DATA LOADEDR FUNCTION(preparing dataset)
# =====================

#image preprocessing
class CustomImageDataset(Dataset):
    def __init__(self, image_paths, transform):
        self.image_paths = image_paths
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        path = self.image_paths[idx]
        img = Image.open(path).convert("RGB")
        img = self.transform(img)

        class_name = os.path.basename(os.path.dirname(path))
        label = CLASS_TO_IDX[class_name]

        return img, label
#image instantiation
train_dataset = CustomImageDataset(train_paths, train_transform)
val_dataset   = CustomImageDataset(val_paths, val_transform)
#Main Dataloader( loading the train/val dataset, setting batches of data that will be fed to modell so 16vimages at time)
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True,
    num_workers=NUM_WORKERS,pin_memory=True)#num workers is the parraellel loading of data and pin_memory is for the data memory set that wont be loaded on local disk

val_loader = DataLoader(val_dataset,batch_size=BATCH_SIZE,shuffle=False,
    num_workers=NUM_WORKERS,pin_memory=True) #easier shift from cpu to gpu

# =====================
# MODEL
# =====================
weights = ViT_B_16_Weights.IMAGENET1K_V1
model = vit_b_16(weights=weights)
model.heads.head = nn.Linear(model.heads.head.in_features, NUM_CLASSES) #final nn layer is called head.
#ImageNet model was trained on  1000 classes so the pretrained ones need to be remodified and recalculated
#takes high-level image features as inputproduces one score (logit) per class and then features of that class

model.to(DEVICE) #model obeject will give computation to gpu

criterion = nn.CrossEntropyLoss() #loss function
optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=0.05)

scheduler = lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", factor=0.1, patience=5
)

# =====================
# TRAINING
# =====================
def train_model(model, epochs):
    best_acc = 0.0 #just accuracy

    for epoch in range(epochs):
        print(f"\nEpoch {epoch+1}/{epochs}")
        print("-" * 30) #this is just to print

        for phase, loader in [("train", train_loader), ("val", val_loader)]:
            model.train() if phase == "train" else model.eval() #loading the gesture classes in phase

            #if phase (taking binary value of train or val will be in either train(train) eval(val))

            running_loss = 0.0 #total loss of that epoch  is initialised
            running_corrects = 0.0 #total correct predictions

            for imgs, labels in loader:
                imgs = imgs.to(DEVICE) #will be converted to tensors
                labels = labels.to(DEVICE)  #ground truth class labels

                optimizer.zero_grad() #gradients for loss are re-calculated and previous ones from imageNet are removed

                with torch.set_grad_enabled(phase == "train"):
                    outputs = model(imgs) #gradient tracking for the weights is enabled if in train phase else disabled
                    loss = criterion(outputs, labels) #prediction vs correct label loss calc
                    preds = torch.argmax(outputs, 1) #prediction of maximum value (most likely class)

                    if phase == "train":
                        loss.backward() #backpropagation will inly happen during training
                        optimizer.step() #step based incrementing weights done by ADAM

                running_loss += loss.item() * imgs.size(0) #running loss on that epoch calculated
                running_corrects += torch.sum(preds == labels)

            epoch_loss = running_loss / len(loader.dataset) #computing overall loss
            epoch_acc = running_corrects.double() / len(loader.dataset) #coputing accuracy

            print(f"{phase.capitalize()} | Loss: {epoch_loss:.4f} | Acc: {epoch_acc:.4f}")

            #validation phase
            if phase == "val":
                scheduler.step(epoch_loss) #The scheduler checks whether the validation loss has improved.

                if epoch_acc > best_acc: #accuracy is checked
                    best_acc = epoch_acc
                    torch.save(
                        model.state_dict(), #contains all learned weights and biases. Saving only the best model ensures you keep the most performant version.
                        os.path.join(SAVE_DIR, "best_vit.pth")
                    )

    print("Training completed.")
    print("Best validation accuracy:", best_acc.item())

# =====================
# RUN
# =====================
if __name__ == "__main__":
    train_model(model, EPOCHS)